### ISSUE TITLE
Version of coq used in the pre-extracted data

### ISSUE THREAD

**Issue by HelingZhang** [princeton-vl/CoqGym#1]
Would you specify the version of coq you used to extract the benchmark data? The downloaded data seems to be incompatible with the newest version of coq.

**Comment by yangky11** [comment]
Hi,

The `./coq` directory in the repo contains a slightly modified version of Coq 8.9.  CoqGym is only compatible with this particular version, as it adds some APIs to the original Coq 8.9 for serializing the variables in the global environment.

**Comment by HelingZhang** [comment]
I see--thanks for the clarification.
