### ISSUE TITLE
How to Use Singularity Containers for Parallel Computing?

### ISSUE THREAD

**Issue by ngundotra** [princeton-vl/CoqGym#11]
It seems that the majority of time is spent in the authors’ modified version of Coq, and that the Singularity containers are meant to spread some of that work out across multiple instances to speed up training. I'm currently able to train ASTTactic on AWS, however, it takes a few days. 

Do you guys have any advice on how we can speed this up?

CC: @daniel-zeng, @zyx0wu

**Comment by yangky11** [comment]
Hi,

I'm not sure if I understand the question correctly. During training, the model just learns to predict the ground truth tactic without really executing that tactic. So there shouldn't be any time spent in Coq?
