### ISSUE TITLE
Does the CoqGym data set contain the Coq Standard Library?

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#12]
Does the CoqGym data set contain the Coq Standard Library (https://github.com/princeton-vl/CoqGym/tree/master/coq_projects)  and was the checkpoint trained on the Coq Standard library?

**Comment by yangky11** [comment]
Yes, CoqGym includes Coq Standard Library: https://github.com/princeton-vl/CoqGym/blob/master/coq_projects/coq.
The pre-trained model was trained on the entire CoqGym, not limited to the standard library.

**Comment by brando90** [comment]
> Yes, CoqGym includes Coq Standard Library: https://github.com/princeton-vl/CoqGym/blob/master/coq_projects/coq.
> The pre-trained model was trained on the entire CoqGym, not limited to the standard library.

I saw https://github.com/princeton-vl/CoqGym/blob/master/coq_projects/coq what is that?

**Comment by brando90** [comment]
@yangky11 how do I train an agent without using the Coq Standard Library?

**Comment by yangky11** [comment]
It is a symbolic link to the coq installation, including the Coq Standard Library.
You should be able to train without the standard library by downloading the data and manually removing the standard library part.
