### ISSUE TITLE
Code for bottom up tree traversal and parser for terms str to AST

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#14]
Hi,

I was wondering if I could be pointed to the right place for these two things:

1) The code that traverses the AST term object from the bottom to the top
2) The code that converts the Coq term (string) to the AST object.

Thanks in advance!

**Comment by yangky11** [comment]
1. In the [TermEncoder](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L126) class, we calculate the node embeddings from bottom to top.  
2. In the [GallinaTermParser](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/gallina.py#L22) class, we use [lark](https://github.com/lark-parser/lark) to parse the S-expressions of Coq terms into ASTs.

**Comment by brando90** [comment]
> 1. In the [TermEncoder](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L126) class, we calculate the node embeddings from bottom to top.
> 2. In the [GallinaTermParser](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/gallina.py#L22) class, we use [lark](https://github.com/lark-parser/lark) to parse the S-expressions of Coq terms into ASTs.

Thanks! Also, do you embed individual symbols? (e.g. characters?) There are 128 chars so what is the point of embedding those? Asking after reading the paper, will attach relevant parts that are unclear to me:

![Screen Shot 2020-12-08 at 8 49 56 AM](https://user-images.githubusercontent.com/1855278/101499938-768d0200-3933-11eb-87f1-5f25767eef1f.png)
![Screen Shot 2020-12-08 at 8 51 50 AM](https://user-images.githubusercontent.com/1855278/101499947-77259880-3933-11eb-9352-24d4f5706b68.png)

**Comment by brando90** [comment]
so do you embed symbols or use one hot vectors for them is basically my question.

**Comment by yangky11** [comment]
We use embeddings. See https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/tactic_decoder.py#L80, 

where the embedding dimension is 256: https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/options.py#L40
