### ISSUE TITLE
How is the mapping of individual words (or symbols) to vectors is done

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#15]
I was wondering what the vocabulary was that coqgym was using. I read in the paper that it was mostly one hot vectors that were being fed directly. Can I:

1) get a confirmation that this is true or not?
2) link to the code that does the mapping of raw (string) word/symbol to embedding i.e. F:Word->Vector? (even if its one-hot)
3) where the collection of the vocabulary is done?

Thanks!

**Comment by yangky11** [comment]
Yes, we use one-hot encoding of the nonterminal symbols in ASTs.
This is the vocabulary: [nonterminals](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L14).
[Here](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L157) is how we calculate the one-hot vectors.

**Comment by brando90** [comment]
> Yes, we use one-hot encoding of the nonterminal symbols in ASTs.
> This is the vocabulary: [nonterminals](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L14).
> [Here](https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/ASTactic/models/term_encoder.py#L157) is how we calculate the one-hot vectors.

Thanks for the reply. 

Are those nonterminals part of the simple atomic tactic grammar you designed for the original paper or are those all the nonterminals available for the Coq language (thus specifying fully the Coq language e.g. programs, terms, tactics, etc)? Or what are they?

**Comment by yangky11** [comment]
They are nonterminals in the ASTs of [Gallina terms](https://coq.github.io/doc/v8.9/refman/language/gallina-specification-language.html#term), so they have nothing to do with tactics. Their corresponding implementation in Coq is in [kernel/constr.ml](https://github.com/princeton-vl/CoqGym/blob/master/coq/kernel/constr.ml).
