### ISSUE TITLE
discussion feature from github for CoqGym

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#18]
Hi!

I recently discovered this the discussion feature from github. Since it seems beyond myself there have been gitissued raised that seem more like questions or discussions I thought this might be a feature you'd like. I am trying it out in my own fork of your repo:

https://github.com/brando90/CoqGym/discussions 

let me know if you open one!

Happy coding proving!

**Comment by yangky11** [comment]
That's an awesome idea. I have opened Disucssions. Thanks!
