### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by corwin-of-amber** [princeton-vl/CoqGym#2]
I found the ICML 2019 paper and I wanted to try out the tool. There is extensive documentation about building and about the data format, but how do I actually use it to see when it is able to predict tactics in Coq proofs?

I managed to run `eval_env.py` and it runs on `data/StructTact/Assoc.json` and indeed it terminates without error as described, but it produces the result `GIVEN_UP` for all the lemmas. What else can I try?

**Comment by yangky11** [comment]
Hi,

Did you try the instructions in Sec. 5 of the README?

**Comment by corwin-of-amber** [comment]
Thanks for the reply! I tried to run it but it takes a long time and the README suggested that it was optional – I guess since one can use the pre-trained model. Can I just run the pre-trained on just one proof?

**Comment by yangky11** [comment]
Yeah, you don't have to train the model. You can download the model following the link in Sec. 5.3. Then you can run it on one proof following the instructions in Sec. 5.4. Just replace the model path with your actual model path.

**Comment by corwin-of-amber** [comment]
I managed to make it work -- it took a bit of effort to get `model.pth` into the container since I'm not familiar with Vagrant and Singularity (perhaps you should include it in your container image?), and it gives some output!
```
python evaluate.py ours ours-TEST --path ~/model.pth 
   --file ../data/StructTact/Assoc.json
   --proof assoc_set_same --output_dir /tmp
```
```js
{"options": {"method": "ours", "eval_id": "ours-TEST", "datapath": "../data", "projs_split": "../projs_split.json", "split": "test", "file": "../data/StructTact/Assoc.json", 
"proof": "assoc_set_same", "filter": null, "path": "/home/vagrant/model.pth", "output_dir": "/tmp", "max_num_tactics": 300, "timeout": 600, "hammer_timeout": 100, "depth_limit": 50, "beam_width": 20, "num_tactic_candidates": 20, "lens_norm": 0.5, "tac_grammar": "tactics.ebnf", "term_embedding_dim": 256, "size_limit": 50, "embedding_dim": 256, "symbol_dim": 256, "hidden_dim": 256, "seed": 0}, "results": [{"filename": "../data/StructTact/Assoc.json", "proof_name": "assoc_set_same", "success": false, 
"proof_gt": ["intros.", "induction l; simpl in *; auto; try congruence.", "repeat break_match; simpl in *; intuition.", "-", "subst.", "find_inversion.", "auto.", "-", "repeat find_rewrite.", "auto."], 
"proof_pred": ["intro.", "intro.", "intro.", "revert l.", "intro.", "revert k.", "intro.", "revert l.", "intro.", "revert v.", "intro.", "revert k.", "intros.", "intuition."], "time": 7.49000096321106, "num_tactics": 300}]}
```

I am guessing `proof_pred` is the predicted proof?

**Comment by yangky11** [comment]
I'm glad you were able to make it work. In this particular example, the prover fails to generate a correct proof. `proof_pred` is not the predicted proof, but the sequence of tactics it tried. As mentioned in the paper, it generates 20 tactics at each step and then performs a depth-first search (DFS). `proof_pred` is just the tactics tried during DFS. However, when it finds a proof successfully, `proof_pred` will be the predicted proof.

**Comment by corwin-of-amber** [comment]
Ok, I now realize that running with the `ours` parameter corresponds to tactic prediction with only the most basic tactics, not even `auto`. I managed to get the same lemma to succeed with `ours+hammer`. Awesome! Can you perhaps release a list of example proofs that were successful with the three different configurations? That might help users trying out the tool get a quick feel.

**Comment by yangky11** [comment]
Yes, it uses only the basic tactics, but that includes "auto" as well. The space of tactics is defined in [this file](https://github.com/princeton-vl/CoqGym/blob/master/ASTactic/tactics.ebnf). 

Great suggestion! I'll add some example proofs when I get a chance. Thank you!
