### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#20]
what does this parsing error mean?

```
Traceback (most recent call last):
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-b0f6a80bf848>", line 59, in <module>
    test_seperate_term_from_hash_lasses_data()
  File "<ipython-input-3-b0f6a80bf848>", line 51, in test_seperate_term_from_hash_lasses_data
    coqgym_parser = gallina.GallinaTermParser()
  File "/Users/brando/CoqGym/gallina.py", line 34, in __init__
    self.parser = Lark(StringIO(self.grammar), start='constr__constr', parser='lalr')
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/lark/load_grammar.py", line 979, in load_grammar
    new_td, new_rd = import_from_grammar_into_namespace(g, '__'.join(dotted_path), aliases)
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/lark/load_grammar.py", line 751, in import_from_grammar_into_namespace
    term_defs.append([get_namespace_name(symbol, None), imported_terms[symbol]])
KeyError: Token('TERMINAL', 'STRING_INNER')
```

**Comment by yangky11** [comment]
It means lark fails to parse `self.grammar`
https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/gallina.py#L27.

I have encountered this error before and it was because my lark version was incorrect. Please check if your lark version is exactly 0.6.5 as in 
https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/coq_gym.yml#L10

**Comment by brando90** [comment]
> It means lark fails to parse `self.grammar`
> https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/gallina.py#L27
> 
> .
> I have encountered this error before and it was because my lark version was incorrect. Please check if your lark version is exactly 0.6.5 as in
> https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/coq_gym.yml#L10

Thanks!

How do you install things from that file? (sorry if my workflow is different, might be nice to include this in your readme since you also have non standard things e.g. you don't have a `setup.py` file or a project + packages hierarchy which is more common for python projects/repos e.g. like this https://packaging.python.org/tutorials/packaging-projects/ that's what I usually use but yours might be better!)

Usually, I have a `install.sh` I simply run (which would be what yours has except it would also have my pip and conda commands).

Thanks for the quick replies!

**Comment by brando90** [comment]
> > It means lark fails to parse `self.grammar`
> > https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/gallina.py#L27
> > 
> > .
> > I have encountered this error before and it was because my lark version was incorrect. Please check if your lark version is exactly 0.6.5 as in
> > https://github.com/princeton-vl/CoqGym/blob/8c15f0d75acfd5a40b0626c41a600aba4000683a/coq_gym.yml#L10
> 
> Thanks!
> 
> How do you install things from that file? (sorry if my workflow is different, might be nice to include this in your readme since you also have non standard things e.g. you don't have a `setup.py` file or a project + packages hierarchy which is more common for python projects/repos e.g. like this https://packaging.python.org/tutorials/packaging-projects/ that's what I usually use but yours might be better!)
> 
> Usually, I have a `install.sh` I simply run (which would be what yours has except it would also have my pip and conda commands).
> 
> Thanks for the quick replies!

this might be useful for yml installations:

https://stackoverflow.com/questions/54492671/how-to-install-list-of-python-libraries-using-yml-file-without-making-new-enviro 

```
You can use the conda env update command:

conda env update --name <your env name> -f <your file>.yml
or, if the environment you want to update is already activated, then

conda env update -f <your file>.yml
```

-----

```
conda env update -f ~/CoqGym/coq_gym.yml
```

or 

```
conda env create -f ~/CoqGym/coq_gym.yml
```

**Comment by yangky11** [comment]
In Sec 1.2 of README:

> 6. Create and activate the conda environment: conda env create -f coq_gym.yml && conda activate coq_gym


For more information about conda environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
