### ISSUE TITLE
Embeddings for tactics

### ISSUE THREAD

**Issue by vrjmath** [princeton-vl/CoqGym#27]
In the function beam_search in Prover.py, it looks like embeddings for environment, context, and goal are created using TermEncoder.py. Then these lines are called: 
https://github.com/princeton-vl/CoqGym/blob/37f93ce320eb6231758024caff39a0f6faaf6825/ASTactic/models/prover.py#L74-L80

Finally, a tactic is outputted with 
https://github.com/princeton-vl/CoqGym/blob/37f93ce320eb6231758024caff39a0f6faaf6825/ASTactic/models/prover.py#L81

I can't seem to find if the tactic is ever embedded through that process. I had two questions: 
1) Is it possible to create embeddings for tactics using TermEncoder.py? (Could I take the output of the decoder and use TermEncoder.py to create an embedding for it?
2) What do those lines above in the function beam_search do?

**Comment by yangky11** [comment]
To clarify, [terms](https://coq.github.io/doc/v8.9/refman/language/gallina-specification-language.html) are [tactics](https://coq.github.io/doc/v8.9/refman/proof-engine/ltac.html) are completely different. Terms are expressions in Coq's functional language. They are used to represent, functions, logical statements, etc. For example, `1+1=2` is a term. In contrast, tactics come from a different language (called tactic language). E.g., `simpl.` is a tactic that can prove `1+1=2`.

This piece of code is only for encoding terms:
https://github.com/princeton-vl/CoqGym/blob/37f93ce320eb6231758024caff39a0f6faaf6825/ASTactic/models/prover.py#L72-L80

The last line generates the tactic from term embeddings:
https://github.com/princeton-vl/CoqGym/blob/37f93ce320eb6231758024caff39a0f6faaf6825/ASTactic/models/prover.py#L81

Details of tactic generation are in https://github.com/princeton-vl/CoqGym/blob/master/ASTactic/models/tactic_decoder.py

**Comment by vrjmath** [comment]
Got it, thanks. Also, I meant to put this question under discussions. Could you move it if possible?

**Comment by brando90** [comment]
see this: https://github.com/princeton-vl/CoqGym/discussions/30 @vrjmath  moved the question for you.

(sorry thought it'd let me close the issue for us)
