### ISSUE TITLE
EOF error while running eval_env.py

### ISSUE THREAD

**Issue by binpeng2** [princeton-vl/CoqGym#3]
Hi, I have followed the setup instructions. (Install Coq, SerAPI and CoqHammer, Build the Coq projects download pre-extracted data and unzip, setup opam and conda env, install other packages). I am using v18 Ubuntu system. However, while running eval_env.py, the terminal always told me an EOF error:

(coq_gym) robin@robin-Blade-Stealth:~/Workspace/DiffCoqGym$ python eval_env.py
/home/robin/Workspace/DiffCoqGym/data/additions/binary_strat.json
Traceback (most recent call last):
  File "eval_env.py", line 232, in <module>
    with FileEnv(f, max_num_tactics=100, timeout=600) as file_env:
  File "eval_env.py", line 133, in __init__
    self.serapi = self.initialize_serapi()
  File "eval_env.py", line 137, in initialize_serapi
    serapi = SerAPI(timeout=1200)
  File "/home/robin/Workspace/DiffCoqGym/serapi.py", line 73, in __init__
    self.proc.expect_exact('(Feedback((doc_id 0)(span_id 1)(route 0)(contents Processed)))\0')
  File "/home/robin/.conda/envs/coq_gym/lib/python3.7/site-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/home/robin/.conda/envs/coq_gym/lib/python3.7/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/home/robin/.conda/envs/coq_gym/lib/python3.7/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF).
<pexpect.popen_spawn.PopenSpawn object at 0x7f8897bd3240>
searcher: searcher_string:
    0: '(Feedback((doc_id 0)(span_id 1)(route 0)(contents Processed)))\x00'

I am guessing that might be issues about pexpect package or Coq version, but I still got this message even if I uninstalled my Coq 8.11.0. And I've never seen similar error message online. Do you have any idea about what accounts for the problem and how to fix it if possible? Thank you for your help.

**Comment by yangky11** [comment]
Hi,

`pexpect` is used to communicate with `serAPI` and it raises [EOF](https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.EOF) often when the child process has exited. So this is likely to be a problem with `serAPI` exits unexpectedly. Could you please:

1. Check if `SerAPI` is installed properly: Run serAPI in the command line using the command `sertop`.  You may have to run `eval $(opam env)` if `sertop` cannot be found.

2. 
Change Line 73 in serapi.py from

```python
self.proc.expect_exact('(Feedback((doc_id 0)(span_id 1)(route 0)(contents Processed)))\0')
```

to

```python
try:
    self.proc.expect_exact('(Feedback((doc_id 0)(span_id 1)(route 0)(contents Processed)))\0')
except pexpect.exceptions.EOF:
    print(self.proc.before)
```

It prints the output of `serAPI` before the EOF error happens.

**Comment by binpeng2** [comment]
Hi yang, thank you for your response. After re-installing serAPI as well as Coq I solve the problem. Thank you very much.
