### ISSUE TITLE
line 6: unrecognized keyword ignored: db_pagesize

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#39]
This might not be a big deal but wanted to let you know the unzip python file gives this warning:

```
tar -xvzf sexp_cache.tar.gz
x sexp_cache.lmdb
mdb_load -f sexp_cache.lmdb sexp_cache
mdb_load: line 6: unrecognized keyword ignored: db_pagesize
```

**Comment by yangky11** [comment]
I had this too some time ago. It might due to different versions of lmdb. But it doesn't seem to cause any problem.
