### ISSUE TITLE
Error when installing SerAPI

### ISSUE THREAD

**Issue by zhaoyu-li** [princeton-vl/CoqGym#4]
Hi, I follow your instructions to install CoqGym from scratch, but I encounter a problem when installing SerAPI. When I run sudo ./install.sh in CoqGym, my terminal always tells me an error when installing:

File "serapi/serapi_protocol.mli", line 135, characters 23-32:
Error (warning 3): deprecated: Sexplib.Conv.sexp_list
[since 2019-03] use [@sexp.list] instead
File "serapi/serapi_protocol.mli", line 136, characters 16-27:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 180, characters 23-34:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 183, characters 21-32:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 184, characters 21-32:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 185, characters 21-32:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 199, characters 37-48:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
File "serapi/serapi_protocol.mli", line 202, characters 61-72:
Error (warning 3): deprecated: Sexplib.Conv.sexp_option
[since 2019-03] use [@sexp.option] instead
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 1
Error: The following <package>.install are missing:
- _build/default/coq-serapi.install

From https://gitter.im/coq-serapi/Lobby?at=5e0cbdddeaa2cd096fd8bcfb, it seems like that the latest version sexplib and ppx_import don't support the version of SerAPI in your project. Do you have any idea about this problem and how to fix it if possible? Thank you for your help.

**Comment by yangky11** [comment]
Hi,

Thanks for your feedback. I'm looking into it and will post an update.

Best,

**Comment by zhaoyu-li** [comment]
Hi, thanks for your attention! It seems like that I should also install camlp5 manually to install SerAPI as well :).

**Comment by yangky11** [comment]
Yes, camlp5 has to be installed. I guess previously it was installed automatically as a dependency of an OPAM package in ./install.sh, e.g., let's say a package `A`. However, maybe the new version of `A` does not depend on camlp5 anymore so it's not automatically installed anymore.  Did you run into any other installation problems after manually installing campl5?

**Comment by zhaoyu-li** [comment]
It's ok to install camlp5 by running `opam install camlp5` and there is no more other problems. The only problem is the first one I mention above :).

**Comment by yangky11** [comment]
I updated install.sh to include the versions of the dependencies. Hopefully, it will resolve the issue you encountered. You can remove the repo on your computer and try installing it again with the new repo.

**Comment by zhaoyu-li** [comment]
Hi, thanks for your quick responce! However, after installing Coq, SerAPI and CoqHammer successfully, I encounter another problem when building the Coq projects by running `sudo make` in coq_projects:

make core-dependencies
make[1]: Entering directory '/home/ubuntu/CoqGym/coq_projects'
make math-comp
make[2]: Entering directory '/home/ubuntu/CoqGym/coq_projects'
cd math-comp/mathcomp/ && make && make install
make[3]: Entering directory '/home/ubuntu/CoqGym/coq_projects/math-comp/mathcomp'
/bin/sh: coqtop: command not found
/bin/sh: coqtop: command not found
/bin/sh: line 0: [: =: unary operator expected
coq_makefile  -f Make -o Makefile.coq
make[3]: coq_makefile: Command not found
Makefile.common:46: recipe for target 'Makefile.coq' failed
make[3]: *** [Makefile.coq] Error 127
make[3]: Leaving directory '/home/ubuntu/CoqGym/coq_projects/math-comp/mathcomp'
makefile:39: recipe for target 'math-comp' failed
make[2]: *** [math-comp] Error 2
make[2]: Leaving directory '/home/ubuntu/CoqGym/coq_projects'
makefile:16: recipe for target 'core-dependencies' failed
make[1]: *** [core-dependencies] Error 2
make[1]: Leaving directory '/home/ubuntu/CoqGym/coq_projects'
makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

It's quite strange that it's ok to use coqtop in the terminal and I set the PATH by running `export PATH=~/CoqGym/coq/bin:$PATH`. Do you have any idea about this problem and how to fix it if possible? Thank you for your help again:).

**Comment by yangky11** [comment]
I'm unable to reproduce this error. What is the output of `which coqc` and `which coqtop` before running `make` in the coq_projects directory?

**Comment by zhaoyu-li** [comment]
The output is `/home/ubuntu/CoqGym/coq/bin/coqc` and `/home/ubuntu/CoqGym/coq/bin/coqtop`, is there something wrong? (I think the path of coqtop is right).

**Comment by yangky11** [comment]
The paths look correct. Can you try running `make` without `sudo`? It compiles the code in coq_projects locally so you don't really need `sudo`.  My hypothesis is that by using `sodu`, you were executing the command in a different shell environment in which `coqtop` could not be found.

**Comment by zhaoyu-li** [comment]
Thanks for your responce! `coqtop` can be found if I don't use `sudo`. However if I don't use `sudo`, there is another problem when running `make` and that's why I use `sudo`:

make[3]: Entering directory '/home/ubuntu/CoqGym/coq_projects/math-comp/mathcomp'
/home/ubuntu/CoqGym/coq/bin/coq_makefile  -f Make -o Makefile.coq
make -f Makefile.coq --no-print-directory install
install: cannot create directory ‘/home/ubuntu/CoqGym/coq//user-contrib/mathcomp’: Permission denied
install: cannot create directory ‘/home/ubuntu/CoqGym/coq//user-contrib/mathcomp’: Permission denied

**Comment by yangky11** [comment]
Then you should check why you don't have the writing permission for directories in /home/ubuntu/CoqGym/coq/user-contrib.  The entire /home/ubuntu/CoqGym directory should belong to your user (not the root user). And you should have writing permissions to every file in it.

**Comment by zhaoyu-li** [comment]
Ok, thanks for your reply! I will check it soon :).

**Comment by zhaoyu-li** [comment]
Hi, yang! Sorry for reopening this issue again. I successfully install CoqGym two weeks ago. But when I run the experiment of CoqGym, it seems like that it needs more than 16G memory GPU. And when I try to install CoqGym on another server, I encounter another problem when installing CompCert by running `cd coq_projects && make`:

Testing linker support for '-no-pie' / '-nopie' option... yes, '-no-pie'
Testing Coq... version 8.9.1 -- UNSUPPORTED
Error: CompCert requires one of the following Coq versions: 8.9.0, 8.8.2, 8.8.1, 8.8.0, 8.7.2, 8.7.1, 8.7.0, 8.6.1.
Testing OCaml... version 4.07.1 -- good!
Testing OCaml .opt compilers... yes
Testing Menhir... version 20181113 -- good!
Testing GNU make... version 4.1 (command 'make') -- good!
One or several required tools are missing or too old.  Aborting.
makefile:35: recipe for target 'CompCert' failed
make[1]: *** [CompCert] Error 2
make[1]: Leaving directory '/home/lizhaoyu/CoqGym/coq_projects'
makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

When I check the server where CoqGym successfully installed, I find that when I enter `opam show coq`, it shows the version of coq is 8.9.1. However, when I run `cd coq_projects && make` to install CompCert, the terminal tells me the version of coq is 8.9.0:

cd CompCert/ && ./configure x86_64-linux && make
Testing assembler support for CFI directives... yes
Testing linker support for '-no-pie' / '-nopie' option... yes, '-no-pie'
Testing Coq... version 8.9.0 -- good!
Testing OCaml... version 4.07.1 -- good!
Testing OCaml .opt compilers... yes
Testing Menhir... version 20181113 -- good!
Testing GNU make... version 4.1 (command 'make') -- good!

It's very strange and when I successfully downgrade coq from 8.9.1 to 8.9.0, there is a problem when installing cheerios.

make cheerios
make[2]: Entering directory '/home/lizhaoyu/CoqGym/coq_projects'
cd cheerios/ && ./configure && make && make install
Error: Build StructTact before building Cheerios
makefile:66: recipe for target 'cheerios' failed
make[2]: *** [cheerios] Error 1
make[2]: Leaving directory '/home/lizhaoyu/CoqGym/coq_projects'
makefile:16: recipe for target 'core-dependencies' failed
make[1]: *** [core-dependencies] Error 2
make[1]: Leaving directory '/home/lizhaoyu/CoqGym/coq_projects'
makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

I think maybe upgrading the version of CompCert may help:). Do you have any idea about this problem and how to fix it if possible? Thank you for your help again:).

**Comment by yangky11** [comment]
Hi,

The Coq used to compile these projects is the locally-built Coq in this repo, which could be different from the Coq installed in OPAM. The local version is a variant of 8.9.0, so the original output when compiling CompCert was actually correct.

Before running `cd coq_projects && make`, you can run `which coqc` to check that. It should be something like "xxx/yyy/CoqGym/coq/bin/coqc". Now that you may have a corrupted partial compilation, you should run `make clean` in the coq_projects folder to clean up before trying again.

Hopefully that will address your problem.

**Comment by zhaoyu-li** [comment]
Hi yang, thank you for your reply, it works. Thank you very much!
