### ISSUE TITLE
Why does CoqGym not use ML4PG (Machine Learning for Proof General)?

### ISSUE THREAD

**Issue by brando90** [princeton-vl/CoqGym#5]
I came across [ML4PG](https://arxiv.org/pdf/1212.3618.pdf) and was wondering why CoqGym does not use it but chose to use SerAPI instead.

**Comment by brando90** [comment]
https://github.com/ML4PG/ML4PG

**Comment by brando90** [comment]
https://github.com/ML4PG/ML4PG/issues/1

**Comment by yangky11** [comment]
Hi,

We use SerAPI for serializing the internal structures of Coq, e.g., environment, local context, goal, notations, etc. After reading the README of ML4PG, it is not clear to me if ML4PG can also be used for that purpose. It looks like ML4PG focuses on extracting feature vectors from theorems, clustering them, and retrieving similar theorems. I'm not aware of if it can be used to prove theorems.
