### ISSUE TITLE
A little question about CoqGym

### ISSUE THREAD

**Issue by zhaoyu-li** [princeton-vl/CoqGym#50]
Hi, I found that there are some constants (premise) in the environment or goal that have no `term`  and  `type`. For example, 
there is a constant:
physical_path': 'coq_projects/coq/plugins/romega/ReflOmegaCore.vo:I.le_lt_int', 'short_ident': 'le_lt_int', 'qualid': 'SerTop.I.le_lt_int', 'term': None, 'type': None, 'sort': None, 'opaque': None, 'sexp': 'fd7fcdd748b0572ea9a408d07d29016aee494c5b'

Is there something wrong? How can I get its `type` and other attributes? Thanks.

**Comment by yangky11** [comment]
I'll take a look and let you know soon.

**Comment by yangky11** [comment]
Sorry for the delay. It's a busy week. I'll probably take a look over the weekend.

**Comment by yangky11** [comment]
I tracked down the error to this line:
https://github.com/princeton-vl/CoqGym/blob/cde1f3f2cd0fa208ea44085e26cae269eec2bc1b/serapi.py#L391

The `type` is a result of applying [print_constr](https://github.com/princeton-vl/CoqGym/blob/cde1f3f2cd0fa208ea44085e26cae269eec2bc1b/serapi.py#L379) to the S-expression. Internally, it calls SerAPI to convert the S-expression into a string. The result would be `None` if the call to SerAPI fails. It is difficult to figure out why this particular call failed. But in principle, the type information is already encoded in the S-expression.
