### ISSUE TITLE
Location of meta files for dataset

### ISSUE THREAD

**Issue by nitishp1812** [princeton-vl/CoqGym#7]
I was trying to generate the dataset using the relevant instructions. However, there were no .meta files in any of the directories and I was also unable to generate them using the makefiles for each coq project.
Where can I access the .meta files used to build the dataset?

**Comment by yangky11** [comment]
Hi, 

*.meta files are generated by the modified Coq included in this repo. If you cannot find them after compiling the Coq projects, most likely you were not compiling using the right Coq installation. Please run `which coqc` before `make` to double-check.

If you are interested in how *.meta files are generated, please refer to [./coq/toplevel/vernac.ml](https://github.com/princeton-vl/CoqGym/blob/master/coq/toplevel/vernac.ml#L136 )
