### ISSUE TITLE
Usage of pre-trained model

### ISSUE THREAD

**Issue by markmorr** [princeton-vl/CoqGym#73]
Hi,
I am looking for the most direct way to simply apply the pre-trained model to a new dataset that I am preparing. I believe the pre-trained model has to be loaded using `torch.load_state_dict()`, which means that I need to include the class definition. This has produced numerous issues getting the dependencies right so that the code runs without errors. (I am on a Windows machine, and the git clone failed because of some issue with a file named Aux.V). 

All of that is to say, would it be possible to get any additional guidance on the simplest way to apply the pre-trained model to new data? Thank you for any advice!

**Comment by yangky11** [comment]
Hi,

Thanks for your interest in our work. I think it would be great to have more documentation and tutorials on that. However, unfortunately, I do not have enough bandwidth to work on it at this moment. Switching to a Singularity/docker container might help with some of your issues.
