### ISSUE TITLE
why is 'SerTop' special when extracting environment and is 'vernac' 'vernacular file'?

### ISSUE THREAD

**Issue by Desperatesonic** [princeton-vl/CoqGym#8]
https://github.com/princeton-vl/CoqGym/blob/85d3c851bb750bca6113f14e17fa9a15a920c2f2/ASTactic/agent.py#L36
Hi, I am very interested in this project and I try to find the definition of 'SerTop' in glossary but I can't, and I find 'vernacular file' when I search for 'vernac'.
could you shed some lights on these, thanks very much!

**Comment by yangky11** [comment]
Hi,

Thanks for your interest in our project.

qualids starting with "SerTop" are top-level terms defined in a Coq file (rather than imported from another module). The code you are referring to means we use the last 10 top-level terms. I have updated [ASTactic/agent.py](https://github.com/princeton-vl/CoqGym/blob/master/ASTactic/agent.py) to add a comment.

**Comment by sonic202607** [comment]
Thanks a lot, by the way is there any way to filter the irrelevant premises in environment, I saw you mentioned it in the paper

**Comment by yangky11** [comment]
Premise selection is a challenging research problem and I don't think there is a silver bullet. What we can do is to use some heuristics based on either formal methods or machine learning.

In the paper, we use a fairly simple method (there may be a large room for improvement). We consider only the local premises and the last 10 top-level premises. We calculate embeddings for them and then use a neural network to select premises. This is similar to many other works in machine learning + theorem proving, although each method differs in detail.

**Comment by sonic202607** [comment]
非常感谢您的回复，不过关于premise selection在coq这个框架下的处理我还有一个疑问。我看到论文里有时候会有上万个premises和证明相关，但这些premises应该没有都用到（猜测，这一点我不太确定哈），有没有办法根据代码里函数的依赖分离出一些没有用到的函数（不是基于机器学习的方法，而是从编译里看有没有调用），如果要调用某个tactic（这个tactic可能会依赖一些premise，换句话说把tactic看成它本身和一些基础函数的集合），这时候再把相关的premise纳入进来。您觉得这是一个可行的研究方向吗

**Comment by yangky11** [comment]
论文中所说的premise是指的当前环境中所有可用的变量，其中绝大多数的确没法用到某个具体的tactic中（因为类型不匹配，强行使用的话会抛出错误）。确实有可能在使用机器学习之前先利用类型信息排除掉很多premises，但是具体实现过程并不trivial，需要有一个高效的方法在不使用一个tactic的前提下判断哪些premises是applicable的。 

关于你所说的“根据代码里函数的依赖”，我认为在testing中可能比较困难。因为输入只有定理的表述而不包含证明，而且环境中所包含的premises可能也和training中遇到过的完全不一样。

**Comment by sonic202607** [comment]
非常感谢您的解答，仔细想想testing确实很难处理这个问题。最后还有一个小问题哈，很好奇实验中用到的所有证明目标goal的定理的表述有没有依赖一些比较高级的premise（某些原项目作者基于简单类型建造的自定义类型）。假如普遍存在这样的现象，使用类似内联函数的方法把这些高级的类型换成低级的类型的组合，再拿这个层数更多更具体的tree去做embedding，效果您觉得是不是会好更一些。再次表示对您回复的感谢和开源的感谢，CoqGym是我找到的所有ITP+ATP框架里最易读易用、扩展性能好的开源项目了。

**Comment by yangky11** [comment]
不客气！大家的认可是对我们很大的鼓励。
你所说的思路确实有可能提高性能，我们在CoqGym论文发表后也有做类似的尝试，暂时没有取得效果，不过也有可能是具体实现过程中出了一些问题。

**Comment by sonic202607** [comment]
感谢您的提供的宝贵信息，另外安利一个叫做zulip的讨论平台https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning.20for.20Theorem.20Proving/topic/CoqGym，上面有不少框架的讨论，但很可惜的是CoqGym在我看来是一个比holist更好用（参数输入限制更少，模型无需每次都编译）的平台却没有应有的热度，如果您的团队有新的相关研究可以在上面宣传发布一下，能follow你们的研究是我的荣幸

**Comment by yangky11** [comment]
谢谢！

**Comment by sonic202607** [comment]
hello，我又出现啦，请教一下您认为tactic_decoder里loglikelihood的计算过程有问题不，我自己实验了一下，发现如果按照提交的pullrequest里的代码执行evaluate.py的话，生成的命令普遍变长了一些。我认为现在的代码里的loglikelihood的公式是这样的：
newloglikelihood = 2* loglikelihood + log_cond_prob,相当于每扩展一次，loglikelihood都要差不多翻一小倍，而且loglikelihood是负数，导致长序列优先级变低。
另外如果按照pullrequest改动的话，我认为可以把loglikelihood的normalization去掉。
这个变动应该会对实验结果有很大的影响，希望能得到你们的确认，到底代码逻辑应不应该这样修改

**Comment by yangky11** [comment]
你好，我大概看了一下，你说的应该是对的。pull request待我和同事讨论之后会接受。如果你在后续实验中发现这个修改后对实验结果有较大影响，也请告知我们。非常感谢！

**Comment by sonic202607** [comment]
hello, 由于计算资源有限我这边只在一小部分project里使用官方提供的model.pth对比了三种情况哈：
情况一： 更改后的代码，如果采用lens_norm = 0.5,那么表现是最差的，生成的平均命令长度也是最长的
情况二：更改后的代码，如果采用lens_norm = 0,那么表现和情况三差不多
情况三：更改前的代码，如果采用lens_norm = 0.5 那么表现和情况二差不多
我个人猜测之所以会有这样的实验结果，可能是因为目前的模型成功的案例大部分都是比较简单的证明，所以不能体现明显的区别，如果后期继续优化模型，按我的预期情况二应该是最好的。。
如果你们有多余的计算资源，可能完整跑一遍全部的项目对比会得到准确的结果，希望这些对你们有帮助哈

**Comment by yangky11** [comment]
好的谢谢！

**Comment by sonic202607** [comment]
hello，为了更好地理解embedding之前的原始数据（去除语法糖后有些时候看不懂sexpr。。。），想请教一下哪里可以找到关于coq去除语法糖后数据格式含义的文档。serapi返回的数据是serapi自己定义的格式还是coq里本身去除语法糖的原始数据格式？无论是serapi_protocol.ml还是coq document里似乎都找不到对应term_encoder里nonterminals的说明，所以又来请教了哈。

**Comment by yangky11** [comment]
在这里应该可以找到：[coq/vernac/vernacexpr.ml](https://github.com/princeton-vl/CoqGym/blob/master/coq/vernac/vernacexpr.ml)

**Comment by sonic202607** [comment]
感谢！不过其实我要找的是AST的说明哈， 比如'constructor_mpfile', 'constructor_mpbound','constructor_mpdot','constructor_dirpath','constructor_mbid','constructor_letstyle'.这其中的后缀。
另外问一下 在gallina.py 里进行解析的时候AST扔掉了符号只保留了树，将embedding的字典浓缩到了55个词，想问问你们之前有没有试过保留全部信息做embedding，再进行实验，效果咋样。再次感谢您的帮助！

**Comment by yangky11** [comment]
这些在这里可以找到：
https://github.com/princeton-vl/CoqGym/blob/05fa4571b2d1e956bc791c4d742a09f550378af1/vernac_types.py#L145
它们其实是用lark-parser解析serapi的output时产生的结果。比如serapi的原始output可能是DirPath，那么在lark-parser输出的AST里面可能就变成了constructor_dirpath.

我们没有尝试过保留token信息。

**Comment by sonic202607** [comment]
非常感谢
