### ISSUE TITLE
Version of pytorch missing from `coq_gym.yml`

### ISSUE THREAD

**Issue by danjenson** [princeton-vl/CoqGym#82]
![image](https://user-images.githubusercontent.com/4793438/221329149-68980ef7-faf7-4b18-9bc3-9b0a2b3c25ab.png)
What version of pytorch do you use for this? It's not specified in your paper either. Thanks!

**Comment by yangky11** [comment]
Hi,

We didn't keep track of the version of PyTorch since it was not used in data generation.  I'd suggest using the latest PyTorch and feel free to follow up here if the code is not compatible with the latest version.
